language: android
jdk: oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-28"
android:
  components:
    - tools
    - build-tools-28
    - android-25
    - extra-android-support
    - extra-android-m2repository
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
