version: 2
jobs:
  build:
    docker:
      - image: behdad222/android-sdk:v2.0.0
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "PersianCalendar/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "PersianCalendar/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: PersianCalendar/build/reports
          destination: reports
      - store_test_results:
          path: PersianCalendar/build/test-results