name: Gradle wrapper update

on:
  workflow_dispatch: # to run the workflow manually if needed
  schedule:
    - cron: '0 12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Upgrade gradle wrapper
        run: |
          ./gradlew wrapper --gradle-version latest
          ./gradlew wrapper --gradle-version latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
        with:
          title: 'Upgrade Gradle version'
          body: ''
          delete-branch: false
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          branch: 'upgrade-gradle-version'
          commit-message: 'Upgrade Gradle version'
