name: Nightly Build

on:
  schedule:
    - cron:  '0 0 * * *' # once a day

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: sudo ./gradlew assembleNightly

      - name: Send apk to telegram
        run: |
          apk_dir="$(find -type f -iname *.apk)"
          curl -F document=@"$apk_dir" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_TO }}
