name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          TEMPLATE: '.[] | "<a href=\"\(.url)\">\(.id[:8])</a> • <a href=\"https://github.com/\(.author.username)\">\(.author.username)</a>

          \(.message)

          "'
        run: |
          (
            printf 'text='
            printenv COMMITS | jq -r "$TEMPLATE"
            printf '📅 @Persian_Calendar'
          ) | \
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d disable_web_page_preview=true \
            -d chat_id=${{ secrets.TELEGRAM_TO }} \
            -d parse_mode=HTML \
            --data-binary @-
