name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        env:
          jsonCommits: ${{ toJson(github.event.commits) }}
        run: |
          (
            printf 'text='

            commits=$(echo $jsonCommits | jq '.')
            length=$(echo $commits | jq 'length')

            for (( i = 0; i < length; i++ )); do
              commit=$(echo $commits | jq '.['$i']')
              url=$(echo $commit | jq -r '.url')
              sha=$(echo $commit | jq -r '.id')
              sha=${sha:0:8}
              actor=$(echo $commit | jq -r '.author.username')
              echo "<a href="\"$url\"">$sha</a> • <a href="\"https://github.com/$actor\"">$actor</a>"
              echo $commit | jq -r '.message'
              echo
            done

            printf '%s' '📅 @Persian_Calendar'
          ) | \
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d disable_web_page_preview=true \
            -d chat_id=${{ secrets.TELEGRAM_TO }} \
            -d parse_mode=HTML \
            --data-binary @-
