name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Building message
        id: building_message
        run: |
          jsonCommits='${{toJson(github.event.commits)}}'
          commits=$(echo $jsonCommits | jq '.')
          length=$(echo $commits | jq 'length')

          outMessage=""
          for (( i = 0; i < length; i++ )); do
            commit=$(echo $commits | jq '.['$i']')
            url=$(echo $commit | jq -r '.url')
            sha=$(echo $commit | jq -r '.id')
            sha=${sha:0:8}
            message=$(echo $commit | jq -r '.message')
            actor=$(echo $commit | jq -r '.author.username')

            outMessage+="<a href="\"$url\"">$sha</a> • <a href="\"https://github.com/$actor\"">$actor</a>"
            outMessage+="%0A"
            outMessage+=$message
            outMessage+="%0A%0A"
          done
          outMessage+="📅 @Persian_Calendar"
          echo "::set-output name=message::$outMessage"

      - name: send message to Telegram
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "$(
              jq -n \
                --argjson disable_web_page_preview true \
                --arg chat_id ${{ secrets.TELEGRAM_TO }} \
                --arg format html \
                --arg text '${{ steps.building_message.outputs.message }}' \
                '$ARGS.named'
            )" \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage
