name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Building message
        run: |
          jsonCommits='${{toJson(github.event.commits)}}'
          commits=$(echo $jsonCommits | jq '.')
          length=$(echo $commits | jq 'length')

          outMessage=""
          for (( i = 0; i < length; i++ )); do
            commit=$(echo $commits | jq '.['$i']')
            url=$(echo $commit | jq -r '.url')
            sha=$(echo $commit | jq -r '.id')
            sha=${sha:0:8}
            message=$(echo $commit | jq -r '.message')
            actor=$(echo $commit | jq -r '.author.username')

            outMessage+="<a href="\"$url\"">$sha</a> • <a href="\"https://github.com/$actor\"">$actor</a>"
            outMessage+="%0A"
            outMessage+=$message
            outMessage+="%0A%0A"
          done
          outMessage+="📅 @Persian_Calendar"

          echo $outMessage
          echo "::set-output name=message::$outMessage"

      - name: send message to Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: ${{ steps.building_message.outputs.message }}
